// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmEKT2Rrzb5l_k9tqqOVe5xuC_inifyME',
    appId: '1:482783383534:web:ce7738fcccc942846088ff',
    messagingSenderId: '482783383534',
    projectId: 'unibuddy-5fe36',
    authDomain: 'unibuddy-5fe36.firebaseapp.com',
    storageBucket: 'unibuddy-5fe36.firebasestorage.app',
    measurementId: 'G-9KSSQFJB5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkuZqOyW9cpQwgv9DY0CuKK7JEJo0zhM',
    appId: '1:482783383534:android:aa1ab413eb9f0c366088ff',
    messagingSenderId: '482783383534',
    projectId: 'unibuddy-5fe36',
    storageBucket: 'unibuddy-5fe36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiyO31fCjAbW52UdEnLKcs90s6iwuKs5k',
    appId: '1:482783383534:ios:21ae60691c5f83e36088ff',
    messagingSenderId: '482783383534',
    projectId: 'unibuddy-5fe36',
    storageBucket: 'unibuddy-5fe36.firebasestorage.app',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiyO31fCjAbW52UdEnLKcs90s6iwuKs5k',
    appId: '1:482783383534:ios:21ae60691c5f83e36088ff',
    messagingSenderId: '482783383534',
    projectId: 'unibuddy-5fe36',
    storageBucket: 'unibuddy-5fe36.firebasestorage.app',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmEKT2Rrzb5l_k9tqqOVe5xuC_inifyME',
    appId: '1:482783383534:web:d7bcef74f30653a56088ff',
    messagingSenderId: '482783383534',
    projectId: 'unibuddy-5fe36',
    authDomain: 'unibuddy-5fe36.firebaseapp.com',
    storageBucket: 'unibuddy-5fe36.firebasestorage.app',
    measurementId: 'G-93ZGNB2950',
  );
}
